#!/bin/sh
# This script is the epitome of sheer laziness. :)
SKEL_DIR="../tsdb/skeletons"
TEST_DIR="$SKEL_DIR/$1"

# Make the directory if it doesn't exist already
if [ ! -d $TEST_DIR ]; then
    mkdir $TEST_DIR
    cp "$SKEL_DIR/Relations" "$TEST_DIR/relations"
fi

./make_item testsuite "$TEST_DIR/item"

